CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL auto_increment,
  `email` varchar(255) NOT NULL default '',
  `new_email` varchar(250) default NULL,
  `password_hash` varchar(255) default NULL,
  `salt` varchar(255) default NULL,
  `tos_accepted_at` datetime default NULL,
  `avatar_id` int(11) default NULL COMMENT 'attachments',
  `username` varchar(50) NOT NULL,
  `activated_at` datetime default NULL,
  `bio` longtext,
  `first_name` varchar(50) default NULL,
  `last_name` varchar(50) default NULL,
  `birthdate` datetime default NULL,
  `city` varchar(50) default NULL,
  `state` varchar(50) default NULL,
  `country` varchar(50) default NULL,
  `home_page` varchar(200) default NULL,
  `age_confirmed_at` datetime default NULL,
  `phone_number` varchar(50) default NULL,
  `cell_number` varchar(50) default NULL,
  `fax_number` varchar(50) default NULL,
  `job_title` varchar(50) default NULL,
  `company_name` varchar(255) default NULL,
  `company_address1` varchar(255) default NULL,
  `company_address2` varchar(255) default NULL,
  `company_city` varchar(50) default NULL,
  `company_state_id` int(11) default NULL COMMENT 'states',
  `company_zip` varchar(10) default NULL,
  `company_country_id` varchar(50) default NULL COMMENT 'countries',
  `company_phone_number` varchar(50) default NULL,
  `tax_id` varchar(50) default NULL,
  `company_incorporation_state_id` varchar(5) default NULL COMMENT 'states',
  `website` varchar(255) default NULL,
  `primary_industry_id` int(11) default NULL COMMENT 'industries',
  `secondary_industry_id` int(11) default NULL COMMENT 'industries',
  `tertiary_industry_id` int(11) default NULL COMMENT 'industries',
  `number_of_employees` int(11) default NULL,
  `date_of_incorporation` datetime default NULL,
  `annual_revenue` varchar(50) default NULL,
  `newsletter_signup` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `email` (`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
